In [ ]:
# 라이브러리 = 모듈 같은 말임!

In [127]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/" # PATH라는 변수에 경로를 미리 넣어두고 불러올 때 사용
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")

In [2]:
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

데이터가 갖고 있는 의미를 파악하는 것이 중요함!!!
FIPS = 각각의 주마다의 코드임! (*나중에 중요하게 나옴)

In [50]:
# 데이터프레임 내 특정 컬럼만 찾아오는 방법
# Country_Region 필드에 속해진 값만 보고 싶어! => ⭐대괄호 표기법으로 입력

Countries = doc["Country_Region"] # 요걸 변수에 담아주자~  doc["Country_Region"] 이렇게만 적어도 물론 나옴 !!!

print(Countries) # 모든 값
print(Countries.head()) # 모든 값 중 가장 위의 5개의 값만

0                   US
1                   US
2                   US
3                   US
4                   US
             ...
2517    United Kingdom
2518             Nauru
2519       New Zealand
2520            Tuvalu
2521    United Kingdom
Name: Country_Region, Length: 2522, dtype: object
0    US
1    US
2    US
3    US
4    US
Name: Country_Region, dtype: object

In [51]:
print(Countries.size) # 그 필드에 들어 있는 모든 데이터의 개수 => 찾아온 데이터의 전체 크기
print(Countries.count()) # *결측치 값을 제외한 정상값을 가지고 있는 데이터의 크기 (이 데이터엔 결측치가 없다~)
# *결측치 = 데이터가 비어 있거나 알 수 없음을 표시하는 값

2522
2522

In [43]:
print(Countries.unique()) # 중복을 제외한 모든 데이터를 나열해줌 (약간 DISTINCT 같은 건가???) => 중복되어있는 데이터들을 대표하는 대표값만 출력
countries.value_counts() # 각각의 데이터가 나온 개수 (COUNT 같은 건가벼) => 그 대표값들의 카운트 횟수

['US' 'Canada' 'United Kingdom' 'China' 'Netherlands' 'Australia'
 'Denmark' 'France' 'Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Austria' 'Azerbaijan'
 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize'
 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi' 'Cabo Verde'
 'Cambodia' 'Cameroon' 'Central African Republic' 'Chad' 'Chile'
 'Colombia' 'Congo (Brazzaville)' 'Congo (Kinshasa)' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus' 'Czechia' 'Diamond Princess'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Fiji' 'Finland' 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana'
 'Greece' 'Grenada' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Holy See' 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran'
 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Korea, South' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg'
 'MS Zaandam' 'Madagascar' 'Maldives' 'Mali' 'Malta' 'Mauritania'
 'Mauritius' 'Mexico' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Namibia' 'Nepal' 'New Zealand' 'Nicaragua' 'Niger'
 'Nigeria' 'North Macedonia' 'Norway' 'Oman' 'Pakistan' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Qatar' 'Romania' 'Russia' 'Rwanda' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino' 'Saudi Arabia'
 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia'
 'Slovenia' 'Somalia' 'South Africa' 'Spain' 'Sri Lanka' 'Sudan'
 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan*' 'Tanzania' 'Thailand'
 'Timor-Leste' 'Togo' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'Uruguay' 'Uzbekistan' 'Venezuela'
 'Vietnam' 'West Bank and Gaza' 'Zambia' 'Zimbabwe' 'Kiribati' 'Palau'
 'Summer Olympics 2020' 'Malaysia' 'Tonga' 'Winter Olympics 2022'
 'Antarctica' 'Korea, North' 'Nauru' 'Tuvalu']

Country_Region
US                      2228
China                     34
United Kingdom            18
Malaysia                  17
Canada                    16
                        ...
Winter Olympics 2022       1
Antarctica                 1
Korea, North               1
Nauru                      1
Tuvalu                     1
Name: count, Length: 190, dtype: int64

In [44]:
#ex) covid_stat = {["A", "B", "C"]} #이렇게 리스트 밖에 또 중첩으로 대괄호를 치면... 저 A,B,C라는 시리즈들을 또다른 데이터 프레임으로...?? 불러올 수 있다?

covid_stat = doc[["Confirmed", "Deaths", "Recovered"]]
covid_stat.head()

   Confirmed  Deaths  Recovered
0          4       0          0
1         47       1          0
2          7       0          0
3        195       3          0
4          1       0          0

#### 🚩 **여까지 저번주에 한 거고 여기부터 새로운 문법들!!!! 새로운 챕터**
- doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig") >>> 이거 불러올 때마다 또또 다른 문법이라고 생각하기~``
- 특정 컬럼 값을 찾아오고 싶을 때 => 대괄호 표기법 (위에서 한 거)
- 그 컬럼 내에서 어떤 조건에 일치하는 값만 가져오고 싶을 때!

In [49]:
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2517,82604.0,NaN,Wales,United Kingdom,2020-04-01 21:58:49,52.130700,-3.783700,0,198,0,0,"Wales, United Kingdom"
2518,NaN,NaN,NaN,Nauru,2020-04-01 21:58:49,-0.522800,166.931500,0,0,0,0,Nauru
2519,NaN,NaN,Niue,New Zealand,2020-04-01 21:58:49,-19.054400,-169.867200,0,0,0,0,"Niue, New Zealand"
2520,NaN,NaN,NaN,Tuvalu,2020-04-01 21:58:49,-7.109500,177.649300,0,0,0,0,Tuvalu
2521,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom"

In [48]:
# 일치하는 값만 찾아서 또다른 series를 만들고 싶을 때 => 컬럼 내 특정 조건에 부합하는 데이터만 찾아올 때 사용
# 1. doc["Country_Region"] 얘를 먼저 적고! 걔가 "US"랑 같다는 조건을 또 대괄호 안에 넣어주기
doc_us = doc[doc["Country_Region"] == "US"] # doc[doc["Country_Region"] == "US"]만 써도 똑같음! 변수 안에 넣으나 안 넣으나~
doc_us

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2246,66000.0,NaN,Guam,US,2020-04-01 21:58:49,13.444300,144.793700,77,3,0,74,"Guam, US"
2273,NaN,NaN,Northern Mariana Islands,US,2020-04-01 21:58:49,15.097900,145.673900,2,0,0,2,",Northern Mariana Islands,US"
2280,NaN,NaN,Puerto Rico,US,2020-04-01 21:58:49,18.220800,-66.590100,286,11,0,275,"Puerto Rico, US"
2285,NaN,NaN,Recovered,US,2020-04-01 21:58:49,0.000000,0.000000,0,0,8474,0,"Recovered, US"
2303,NaN,NaN,Virgin Islands,US,2020-04-01 21:58:49,18.335800,-64.896300,30,0,0,30,",Virgin Islands,US"

In [128]:
# NaN 데이터를 버릴 때???
# NaN = Not a Number (=숫자가 아님) 컴퓨터는 우리가 쓰는 모든 문자를 숫자로 인식허자먼! (*ASCII 코드 참고)
# => 측정할 수 없는 값 (insnull로 찾아냄!)

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.isnull()  # .isnull() : 항상은 아니지만 거의 대부분 불리언 값을 가져옴!!! True = null임

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
2517,False,True,False,False,False,False,False,False,False,False,False,False
2518,True,True,True,False,False,False,False,False,False,False,False,False
2519,True,True,False,False,False,False,False,False,False,False,False,False
2520,True,True,True,False,False,False,False,False,False,False,False,False
2521,True,True,False,False,False,False,False,False,False,False,False,False

In [62]:
doc.isnull().sum() # null값의 총 개수를 sum으로 집계해왔음! 이제 버릴 차례(아래 셀)

FIPS              347
Admin2            301
Province_State    184
Country_Region      0
Last_Update         0
Lat                 4
Long_               4
Confirmed           0
Deaths              0
Recovered           0
Active              0
Combined_Key        0
dtype: int64

In [129]:
# 이제 버릴 차례!!!! drop -> 근데 진짜 지우는 게 아니고 이 실행문에서만 그렇게 보여지는 것!
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc = doc.dropna() # .dropna() : 결측치(na)를 drop 시켜라
doc.isnull().sum() # => 모든 결측치가 0으로 변함!!! 잘 버려졌음!

FIPS              0
Admin2            0
Province_State    0
Country_Region    0
Last_Update       0
Lat               0
Long_             0
Confirmed         0
Deaths            0
Recovered         0
Active            0
Combined_Key      0
dtype: int64

In [69]:
# 다른 데이터 가져와서 또 드랍! (01-22)
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc.dropna()
doc.isnull().sum()
doc.head()

# .dropna() 의 단점...!!! 데이터베이스의 모든 결측치가 다 날라감;;;;;; Confirmed 필드의 결측치만 버리고 싶으면????? (아래로)
# 아예 삭제는 아니고 이 살향문에서만 안 보이게 하는 건가브다!
# dropna() 등의 구문을 실행하게 되면 원본에서 dropna()가 적용된 카피본이 생성됨. 그 카피본에서의 데이터 변화는 영구적이지만 원본데이터는 따로 건드리지 않음

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
13,Hubei,Mainland China,1/22/2020 17:00,444.0,17.0,28.0
41,Cook Islands,New Zealand,1/22/2020 17:00,0.0,0.0,0.0
43,Johor,Malaysia,1/22/2020 17:00,0.0,0.0,0.0
44,Kedah,Malaysia,1/22/2020 17:00,0.0,0.0,0.0
45,Kelantan,Malaysia,1/22/2020 17:00,0.0,0.0,0.0

In [72]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc.head()

doc = doc.dropna(subset=["Confirmed"]) # subset= 부분집합 설정  # Confirmed 내에서만 NaN 값이 사라지고 다른 
doc

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
5,Guangdong,Mainland China,1/22/2020 17:00,26.0,NaN,NaN
...,...,...,...,...,...,...
71,Unknown,United Kingdom,1/22/2020 17:00,0.0,0.0,0.0
72,NaN,Nauru,1/22/2020 17:00,0.0,0.0,0.0
73,Niue,New Zealand,1/22/2020 17:00,0.0,0.0,0.0
74,NaN,Tuvalu,1/22/2020 17:00,0.0,0.0,0.0
75,Pitcairn Islands,United Kingdom,1/22/2020 17:00,0.0,0.0,0.0

In [74]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc.fillna(0) # .fillna() 안에 있는 인자값으로 결측치를 대체한다!!
doc.head() # NaN으로 뜨던 애들이 다 0으로 바뀜! 프로젝트 할 때도 dropna로 날리는 것보다 fillna로 0으로 채우는 게 나을 수 있음!

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [75]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
nan_data = {"Deaths":0, "Recovered":0} # 딕셔너리 형식으로 하나의 형식을 만듦! 얘를 fillna()의 인자값으로 넣을 것ㅇㅇ
doc = doc.fillna(nan_data) # 대체값(모든걸0으로) / 부분집합으로 적기 싫을 때! 이렇게 사용
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,Gansu,Mainland China,1/22/2020 17:00,NaN,0.0,0.0

#### **GROUPBY** 나옴... 문법이 중고급으로 넘어가고 있다는 뜻~
- 위에서 한 size, unique, counts 이런 애들은 명세서처럼 데이터를 보여 주기만 하는 거고 전처리가 된 건 아님 !!!
- 이제 할 것.
- 그룹화가 되면 *집계*할 수 있다!

In [131]:
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [132]:
doc = doc.groupby("Country_Region").sum()
doc.head()
# 그룹화가 되면 *집계*할 수 있다!
# 그룹화가 되면 자동으로 인덱스가 됨

,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
Country_Region,,,,,,,,,,,
Afghanistan,0.0,0,0,2020-04-01 21:58:34,33.93911,67.709953,192,4,5,183,Afghanistan
Albania,0.0,0,0,2020-04-01 21:58:34,41.15330,20.168300,259,15,67,177,Albania
Algeria,0.0,0,0,2020-04-01 21:58:34,28.03390,1.659600,847,58,61,728,Algeria
Andorra,0.0,0,0,2020-04-01 21:58:34,42.50630,1.521800,390,14,10,366,Andorra
Angola,0.0,0,0,2020-04-01 21:58:34,-11.20270,17.873900,8,2,1,5,Angola

In [85]:
print(doc.columns) # 컬럼들을 보고 싶을 때 (첫 행)
print(doc.index) # 인덱스를 보고 싶을 때 (첫 열) # 아까 groupby를 줬기 때문에 그게 자동으로 인덱스가 됨

Index(['FIPS', 'Admin2', 'Province_State', 'Last_Update', 'Lat', 'Long_',
       'Confirmed', 'Deaths', 'Recovered', 'Active', 'Combined_Key'],
      dtype='object')
Index(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antarctica',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       ...
       'United Arab Emirates', 'United Kingdom', 'Uruguay', 'Uzbekistan',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Winter Olympics 2022',
       'Zambia', 'Zimbabwe'],
      dtype='object', name='Country_Region', length=190)

In [86]:
# 미국을 찾고 싶을 때! index 안에 US가 있을 테니까!
doc[doc.index == "US"]
# doc의 index 값 중에 "US"에 부합하는 값을 ""doc"" 안에서 찾아와! (그래서 doc 안에 대괄호표기법을 쓰는 것이얌!)

,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
Country_Region,,,,,,,,,,,
US,65168934.0,AbbevilleAcadiaAccomackAdaAdairAdairAdairAdams...,South CarolinaLouisianaVirginiaIdahoIowaMissou...,2020-04-01 21:58:492020-04-01 21:58:492020-04-...,82956.96013,-197553.963757,216936,5222,8474,209150,"Abbeville, South Carolina, USAcadia, Louisiana..."

#### 🚩 이제 **하나로 합치는 단계** !! - 또 새로운 챕터
- **여러개의 데이터를 하나로** 모아서 전체 인사이트 정보를 도출하려고 할 때, **꼭 체크해야 하는 유의사항**
1. 각각의 컬럼 안에 입력되어 있는 값의 자료 형태
2. 해당 컬럼을 대표하는 필드명의 동일 여부
3. 수집한 데이터의 결측치 여부 (버릴 거냐 대체할 거냐)
   - 결측치 값을 어떻게 처리할 것인지 결정
---
- 각 데이터들의 컬럼 타입을 맞춰 주기 위한 변경 (ex. 실수 -> 정수)
- 컬럼명이 다를 때...!!!

In [91]:
# 📌 컬럼 타입 변경

import pandas as pd
PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"

In [97]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc[["Country/Region", "Confirmed"]] # 1. 특정 컬럼만 가져오기
doc.info()
# Confirmed는 실수자료형 형태 근데!!! 04-01 데이터의 Confirmed는 정수 형태임...!!!! 일괄 형태로 바꿔주지 않으면 큰 오차/에러 생길 것임 ㅠ!!! 그래서 바꿔주는 거

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country/Region  76 non-null     object
 1   Confirmed       66 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.3+ KB

In [99]:
# 결측치는 버리고 시작함... dropna! *근데 Country/Region에는 결측치가 없으니 Confirmed만 부분집합으로 지정해줌!
doc = doc.dropna(subset="Confirmed") # >>>>>>> *중요 이 과정이 없으면 에러남!!!!!! 특정 컬럼 값을 변경하기 전에 결측치가 존재하면 안 됨!!!!!
doc = doc.astype({"Confirmed": "int64"}) # .astype() 특정 컬럼의 타입을 변경!
doc.info()
# Confirmed의 결측치 10개를 버렸기 때문에 나라 데이터 10개도 같이 버려져서 76에서 66로 변경됐고, 타입은 float64에서 int64로 변경됐음...!!! 이게 전처리 과정 !!!
# 왜 Confirmed의 결측치를 0으로 변경하지 않고 drop을 하느냐! -> 정보의 신뢰도가 떨어짐

<class 'pandas.core.frame.DataFrame'>
Index: 66 entries, 0 to 75
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country/Region  66 non-null     object
 1   Confirmed       66 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.5+ KB

In [134]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc[["Country/Region", "Confirmed"]]
doc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country/Region  76 non-null     object
 1   Confirmed       66 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.3+ KB

In [135]:
doc.head() # 01-22는 컬럼명이 Country/Region이고, 04-01은 Country_Region... 나중에 JOIN 불가능함...!

   Country/Region  Confirmed
0  Mainland China        1.0
1  Mainland China       14.0
2  Mainland China        6.0
3  Mainland China        1.0
4  Mainland China        NaN

In [ ]:
# 필기 놓침...ㅎ.,,,, 컬럼명맞춰주기한거가튼디...!!! 이따 파일 받아서 정리 -> 정리 완료 ^ㅇ^~

In [136]:
doc.columns

Index(['Country/Region', 'Confirmed'], dtype='object')

In [137]:
doc.columns = ["Country_Region", "Confirmed"]
# .columns 라는 속성을 사용해서 컬럼명을 바꿔 주는 거 !!! 이제 다시 doc.columns 입력하면 컬럼명이 "Country_Region"로 바뀌어 있음!

In [138]:
doc.columns

Index(['Country_Region', 'Confirmed'], dtype='object')

In [121]:
# 📌 데이터프레임에서 중복 행 확인/제거

import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"

In [112]:
doc = pd.read_csv(PATH, encoding="utf-8-sig")
doc = doc[["iso2", "Country_Region"]] # 특정 조건 = 중첩대괄호 !!! [[]]
doc # iso2는 왜 찾아왔냐 iso2 : 국가를 대표하는 시그니처 아이디 (국기명 찾아올 때 파일명으로 사용할 거라 필요함!)

     iso2 Country_Region
0      BW       Botswana
1      BI        Burundi
2      SL   Sierra Leone
3      AF    Afghanistan
4      AL        Albania
...   ...            ...
3555   US             US
3556   US             US
3557   US             US
3558   US             US
3559   US             US

[3560 rows x 2 columns]

In [114]:
doc.duplicated() # 해당 인덱스값이 중복된 값이 존재한다면 True! 위에 3555~3559는 US로 중복되었기 때문에 True라고 뜨는 것

0       False
1       False
2       False
3       False
4       False
        ...
3555     True
3556     True
3557     True
3558     True
3559     True
Length: 3560, dtype: bool

In [117]:
doc[doc.duplicated()] # True인(=중복된) 값들만 뜨는 것임!

# 목적 : 현재 여러번 중복해서 사용된 값들을 1개만 남기고 나머지는 제거 (국가코드와 국가명은 1번씩만 나오면 되기 때문에 제거하는 것 같다!)
# 어떤 값을 살리고, 어떤 기준으로 나머지의 값을 제거할 것인가 (아래 셀)

     iso2  Country_Region
194    GB  United Kingdom
200    AU       Australia
201    AU       Australia
202    AU       Australia
203    AU       Australia
...   ...             ...
3555   US              US
3556   US              US
3557   US              US
3558   US              US
3559   US              US

[3353 rows x 2 columns]

In [118]:
doc = doc.drop_duplicates(subset="Country_Region", keep="last")
# Country_Region가 기준이 되어야 하니까 부분집합에 넣어줌! subset=부분집합
# keep= 이라는 옵션 안 주면 기본이 first! last를 적어도 됨 근데 여기선 수치를 구하는 게 아니라서 그렇게 중요하진 않음
# dropna 처럼 drop듀 라고 기억하면 좋을듯!

doc # 3353 rows 에서 180 rows로 확 줄었음!!! US의 중복값이 많아서! china도! US는 마지막 행의 인덱스였던 3559만 남았음!

     iso2  Country_Region
0      BW        Botswana
1      BI         Burundi
2      SL    Sierra Leone
3      AF     Afghanistan
4      AL         Albania
...   ...             ...
198    TC  United Kingdom
206    AU       Australia
221    CA          Canada
254    CN           China
3559   US              US

[180 rows x 2 columns]

In [124]:
# 📌 서로 다른 두 개의 데이터 프레임 연결하기 (파일 새로 만들어서 진행!!) -> pandas 폴더의 [0917] - 0917_pandas_example