In [1]:
import pandas as pd
PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")

In [2]:
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [5]:
# dataframe 내 특정 컬럼만 찾아오는 방법

countries = doc["Country_Region"]
countries

0                   US
1                   US
2                   US
3                   US
4                   US
             ...
2517    United Kingdom
2518             Nauru
2519       New Zealand
2520            Tuvalu
2521    United Kingdom
Name: Country_Region, Length: 2522, dtype: object

In [8]:
print(countries.size, countries.count())
#size : 몇 개의 데이터가 존재하는지 알려주는 함수 (결측치를 제외하고 개수 셈)
#count : NaN을 포함해서 전체 원소 개수를 셈
#찾아온 데이터의 전체 크기, 결측치가 아닌 정상값을 가지고 있는 데이터의 크기

2522 2522

In [9]:
print(countries.unique())
#리스트 형태의 타입으로 대표값을 추출하는 것
#중복되어 있는 데이터들을 대표하는 대표값만 출력

['US' 'Canada' 'United Kingdom' 'China' 'Netherlands' 'Australia'
 'Denmark' 'France' 'Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Austria' 'Azerbaijan'
 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize'
 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi' 'Cabo Verde'
 'Cambodia' 'Cameroon' 'Central African Republic' 'Chad' 'Chile'
 'Colombia' 'Congo (Brazzaville)' 'Congo (Kinshasa)' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus' 'Czechia' 'Diamond Princess'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Fiji' 'Finland' 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana'
 'Greece' 'Grenada' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Holy See' 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran'
 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Korea, South' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg'
 'MS Zaandam' 'Madagascar' 'Maldives' 'Mali' 'Malta' 'Mauritania'
 'Mauritius' 'Mexico' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Namibia' 'Nepal' 'New Zealand' 'Nicaragua' 'Niger'
 'Nigeria' 'North Macedonia' 'Norway' 'Oman' 'Pakistan' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Qatar' 'Romania' 'Russia' 'Rwanda' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino' 'Saudi Arabia'
 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia'
 'Slovenia' 'Somalia' 'South Africa' 'Spain' 'Sri Lanka' 'Sudan'
 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan*' 'Tanzania' 'Thailand'
 'Timor-Leste' 'Togo' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'Uruguay' 'Uzbekistan' 'Venezuela'
 'Vietnam' 'West Bank and Gaza' 'Zambia' 'Zimbabwe' 'Kiribati' 'Palau'
 'Summer Olympics 2020' 'Malaysia' 'Tonga' 'Winter Olympics 2022'
 'Antarctica' 'Korea, North' 'Nauru' 'Tuvalu']

In [10]:
countries.value_counts()
# 대표값들의 카운트 횟수

Country_Region
US                      2228
China                     34
United Kingdom            18
Malaysia                  17
Canada                    16
                        ...
Winter Olympics 2022       1
Antarctica                 1
Korea, North               1
Nauru                      1
Tuvalu                     1
Name: count, Length: 190, dtype: int64

In [14]:
covid_stat = doc[["Confirmed", "Deaths", "Recovered"]]
covid_stat.head

# head : 5개만 뽑아줌
# 여러 열을 고를 때에는 리스트를 넣어야 하기 때문에 중첩 괄호 사용

<bound method NDFrame.head of       Confirmed  Deaths  Recovered
0             4       0          0
1            47       1          0
2             7       0          0
3           195       3          0
4             1       0          0
...         ...     ...        ...
2517          0     198          0
2518          0       0          0
2519          0       0          0
2520          0       0          0
2521          0       0          0

[2522 rows x 3 columns]>

In [21]:
# 특정 조건에 해당되는 값만 추출해오는 방법

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc

# 값을 매칭하기 위해 대괄호 중첩 사용(조건 필터링 문법)
us_data = doc[doc["Country_Region"] == "US"]
us_data

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2246,66000.0,NaN,Guam,US,2020-04-01 21:58:49,13.444300,144.793700,77,3,0,74,"Guam, US"
2273,NaN,NaN,Northern Mariana Islands,US,2020-04-01 21:58:49,15.097900,145.673900,2,0,0,2,",Northern Mariana Islands,US"
2280,NaN,NaN,Puerto Rico,US,2020-04-01 21:58:49,18.220800,-66.590100,286,11,0,275,"Puerto Rico, US"
2285,NaN,NaN,Recovered,US,2020-04-01 21:58:49,0.000000,0.000000,0,0,8474,0,"Recovered, US"
2303,NaN,NaN,Virgin Islands,US,2020-04-01 21:58:49,18.335800,-64.896300,30,0,0,30,",Virgin Islands,US"

In [22]:
# 결측치 데이터가 있다면, 어떻게 결측치를 제거해야 하는가?

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc

#NaN = Not a Number (숫자가 아니라는 뜻)
# 아스키 코드에 의해 우리가 입력하는 모든 문자는 숫자로 이루어져 있음
# 그러니 문자열이 입력되는 시리즈더라도 NaN값이 뜨게 되는 것

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2517,82604.0,NaN,Wales,United Kingdom,2020-04-01 21:58:49,52.130700,-3.783700,0,198,0,0,"Wales, United Kingdom"
2518,NaN,NaN,NaN,Nauru,2020-04-01 21:58:49,-0.522800,166.931500,0,0,0,0,Nauru
2519,NaN,NaN,Niue,New Zealand,2020-04-01 21:58:49,-19.054400,-169.867200,0,0,0,0,"Niue, New Zealand"
2520,NaN,NaN,NaN,Tuvalu,2020-04-01 21:58:49,-7.109500,177.649300,0,0,0,0,Tuvalu
2521,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom"

In [23]:
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.isnull().sum()
# isnull = 값의 유무를 확인할 수 있게 boolean의 형태로 들어옴
# sum = 집계함수

FIPS              347
Admin2            301
Province_State    184
Country_Region      0
Last_Update         0
Lat                 4
Long_               4
Confirmed           0
Deaths              0
Recovered           0
Active              0
Combined_Key        0
dtype: int64

In [25]:
# 값을 제거하고 싶다면 어떻게 해야할까?

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc = doc.dropna()
doc.isnull().sum()
#dropna : na = not a vailable = 가용할 수 없는 값들은 제거시켜라

FIPS              0
Admin2            0
Province_State    0
Country_Region    0
Last_Update       0
Lat               0
Long_             0
Confirmed         0
Deaths            0
Recovered         0
Active            0
Combined_Key      0
dtype: int64

In [29]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc.dropna()
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
13,Hubei,Mainland China,1/22/2020 17:00,444.0,17.0,28.0
41,Cook Islands,New Zealand,1/22/2020 17:00,0.0,0.0,0.0
43,Johor,Malaysia,1/22/2020 17:00,0.0,0.0,0.0
44,Kedah,Malaysia,1/22/2020 17:00,0.0,0.0,0.0
45,Kelantan,Malaysia,1/22/2020 17:00,0.0,0.0,0.0

In [30]:
# dropna는 시리즈별 결측치가 하나만 있어도 나오지 않음
# 그렇다면 결측치가 없는 시리즈가 나오게 하는 방법은 무엇일까?
# 부분집합을 만들어서 나오게 함

doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc.dropna(subset = ["Confirmed"])

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
5,Guangdong,Mainland China,1/22/2020 17:00,26.0,NaN,NaN
...,...,...,...,...,...,...
71,Unknown,United Kingdom,1/22/2020 17:00,0.0,0.0,0.0
72,NaN,Nauru,1/22/2020 17:00,0.0,0.0,0.0
73,Niue,New Zealand,1/22/2020 17:00,0.0,0.0,0.0
74,NaN,Tuvalu,1/22/2020 17:00,0.0,0.0,0.0
75,Pitcairn Islands,United Kingdom,1/22/2020 17:00,0.0,0.0,0.0

In [31]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

# fillna : 결측치들을 임의의 값으로 대체할 수 있게하는 함수
doc = doc.fillna(0)
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [32]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
nan_data = {"Deaths":0, "Recovered" : 0}
doc = doc.fillna(nan_data)
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,Gansu,Mainland China,1/22/2020 17:00,NaN,0.0,0.0

In [35]:
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [38]:
doc = doc.groupby("Country_Region").sum()
doc.head()

#그룹화가 되면 자동으로 index가 생성된다

,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
Country_Region,,,,,,,,,,,
Afghanistan,0.0,0,0,2020-04-01 21:58:34,33.93911,67.709953,192,4,5,183,Afghanistan
Albania,0.0,0,0,2020-04-01 21:58:34,41.15330,20.168300,259,15,67,177,Albania
Algeria,0.0,0,0,2020-04-01 21:58:34,28.03390,1.659600,847,58,61,728,Algeria
Andorra,0.0,0,0,2020-04-01 21:58:34,42.50630,1.521800,390,14,10,366,Andorra
Angola,0.0,0,0,2020-04-01 21:58:34,-11.20270,17.873900,8,2,1,5,Angola

In [39]:
doc.columns

Index(['FIPS', 'Admin2', 'Province_State', 'Last_Update', 'Lat', 'Long_',
       'Confirmed', 'Deaths', 'Recovered', 'Active', 'Combined_Key'],
      dtype='object')

In [40]:
doc.index

Index(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antarctica',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       ...
       'United Arab Emirates', 'United Kingdom', 'Uruguay', 'Uzbekistan',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Winter Olympics 2022',
       'Zambia', 'Zimbabwe'],
      dtype='object', name='Country_Region', length=190)

In [43]:
#미국 정보에 대해 찾아와보자

doc[doc.index == "US"]

,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
Country_Region,,,,,,,,,,,
US,65168934.0,AbbevilleAcadiaAccomackAdaAdairAdairAdairAdams...,South CarolinaLouisianaVirginiaIdahoIowaMissou...,2020-04-01 21:58:492020-04-01 21:58:492020-04-...,82956.96013,-197553.963757,216936,5222,8474,209150,"Abbeville, South Carolina, USAcadia, Louisiana..."

In [44]:
# 컬럼 타입 변경

import pandas as pd
PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"

In [52]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

# 특정 시리즈만 발췌하고 데이터프레임 생성
doc = doc[["Country/Region", "Confirmed"]]
doc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country/Region  76 non-null     object
 1   Confirmed       66 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.3+ KB

In [54]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

doc = doc[["Country/Region", "Confirmed"]]
doc = doc.dropna(subset = ["Confirmed"]) #10개의 na값을 제거하기 위해
doc = doc.astype({"Confirmed" : "int64"})
#특정 시리즈의 타입을 별칭(*as)해준다(변환한다)
doc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66 entries, 0 to 75
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country/Region  66 non-null     object
 1   Confirmed       66 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.5+ KB

In [57]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc[["Country/Region", "Confirmed"]]
doc = doc.dropna(subset = ["Confirmed"])
doc = doc.astype({"Confirmed" : "int64"})
doc

# 결측치의 값을 버리지 않고 타입을 변경해라 > 오류남
# 특정 컬럼의 타입을 변경하기 전에 반드시 결측치값이 존재하면 안 된다

    Country/Region  Confirmed
0   Mainland China          1
1   Mainland China         14
2   Mainland China          6
3   Mainland China          1
5   Mainland China         26
..             ...        ...
71  United Kingdom          0
72           Nauru          0
73     New Zealand          0
74          Tuvalu          0
75  United Kingdom          0

[66 rows x 2 columns]

In [58]:
doc.head()

   Country/Region  Confirmed
0  Mainland China          1
1  Mainland China         14
2  Mainland China          6
3  Mainland China          1
5  Mainland China         26

In [59]:
# 서로 다른 컬럼명을 통일
doc.columns

Index(['Country/Region', 'Confirmed'], dtype='object')

In [61]:
doc.columns = ["Country_Region", "Confirmed"]

In [62]:
doc.columns

Index(['Country_Region', 'Confirmed'], dtype='object')

In [63]:
doc.head()

   Country_Region  Confirmed
0  Mainland China          1
1  Mainland China         14
2  Mainland China          6
3  Mainland China          1
5  Mainland China         26

In [64]:
# 데이터프레임에서 중복 행 확인/제거

import pandas as pd
PATH = "COVID-19-master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"

In [69]:
doc = pd.read_csv(PATH, encoding = "utf-8-sig")
doc

,Unnamed: 0.1,Unnamed: 0,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key
0,0,0,NaN,BW,NaN,NaN,NaN,NaN,NaN,Botswana,NaN,NaN,Botswana
1,1,1,NaN,BI,NaN,NaN,NaN,NaN,NaN,Burundi,NaN,NaN,Burundi
2,2,2,NaN,SL,NaN,NaN,NaN,NaN,NaN,Sierra Leone,NaN,NaN,Sierra Leone
3,3,3,4.0,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.939110,67.709953,Afghanistan
4,4,4,8.0,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.153300,20.168300,Albania
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3555,3555,3555,84056037.0,US,USA,840.0,56037.0,Sweetwater,Wyoming,US,41.659439,-108.882788,"Sweetwater, Wyoming, US"
3556,3556,3556,84056039.0,US,USA,840.0,56039.0,Teton,Wyoming,US,43.935225,-110.589080,"Teton, Wyoming, US"
3557,3557,3557,84056041.0,US,USA,840.0,56041.0,Uinta,Wyoming,US,41.287818,-110.547578,"Uinta, Wyoming, US"
3558,3558,3558,84056043.0,US,USA,840.0,56043.0,Washakie,Wyoming,US,43.904516,-107.680187,"Washakie, Wyoming, US"
3559,3559,3559,84056045.0,US,USA,840.0,56045.0,Weston,Wyoming,US,43.839612,-104.567488,"Weston, Wyoming, US"

In [72]:
# 그룹핑이 아니라 중복되어지는 값을 하나만 찾아오고 싶을 때
doc = pd.read_csv(PATH, encoding = "utf-8-sig")
doc = doc[["iso2", "Country_Region"]]
doc

     iso2 Country_Region
0      BW       Botswana
1      BI        Burundi
2      SL   Sierra Leone
3      AF    Afghanistan
4      AL        Albania
...   ...            ...
3555   US             US
3556   US             US
3557   US             US
3558   US             US
3559   US             US

[3560 rows x 2 columns]

In [73]:
doc.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3555     True
3556     True
3557     True
3558     True
3559     True
Length: 3560, dtype: bool

In [74]:
doc[doc.duplicated()]
# 현재 여러 번 중복되서 사용된 값들을 한 개만 남기고 나머지는 제거
# 어떤 값을 살리고 어떤 기준으로 나머지값을 제거할 것인가에 대한 정의가 필요

     iso2  Country_Region
194    GB  United Kingdom
200    AU       Australia
201    AU       Australia
202    AU       Australia
203    AU       Australia
...   ...             ...
3555   US              US
3556   US              US
3557   US              US
3558   US              US
3559   US              US

[3353 rows x 2 columns]

In [77]:
#중복되어지는 값을 제거
doc = doc.drop_duplicates(subset = "Country_Region", keep = "last")
doc

     iso2  Country_Region
0      BW        Botswana
1      BI         Burundi
2      SL    Sierra Leone
3      AF     Afghanistan
4      AL         Albania
...   ...             ...
198    TC  United Kingdom
206    AU       Australia
221    CA          Canada
254    CN           China
3559   US              US

[180 rows x 2 columns]